//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModelContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Overseer_Name { get; set; }
        public string Overseer_Surname { get; set; }
        public string Practice_No { get; set; }
        public string Tel_Number { get; set; }
        public string Fax_Number { get; set; }
        public string Email_Address { get; set; }
        public string Bank_Name { get; set; }
        public string Branch_Number { get; set; }
        public string Account_Number { get; set; }
        public string Address { get; set; }
    }
}
