//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModelContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildMeasurement
    {
        public int Id { get; set; }
        public double Weight { get; set; }
        public double Height { get; set; }
        public double HeadCircumference { get; set; }
        public System.DateTime Created { get; set; }
        public string ChildID { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
