//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModelContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public System.Guid Id { get; set; }
        public System.Guid VaccinationDefinitionId { get; set; }
        public string IdNumber { get; set; }
        public string Administrator { get; set; }
        public string SerialNumber { get; set; }
        public string Signature { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
