//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModelContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccincationPrice
    {
        public int VaccinationPriceId { get; set; }
        public string VaccinationDefId { get; set; }
        public decimal PriceAmount { get; set; }
    }
}
